on:
  release:
    types: [created]

name: Publish npm package

jobs:
  publish-package:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Rename for Github Registry
        run: |
          npm pkg set name="@votemike/react-accordion"
          npm install --ignore-scripts

      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          access: public
          token: ${{ secrets.GITHUB_TOKEN }}
